comment="--This file is automatically generated at runtime. Any changes to the file will be lost."
name=$(grep -o '"configName": "[^"]*"*' $1 | awk -F '"' '{print $4}') 
proj=$(grep -o '"projectsFileUrl": "[^"]*"*' $1 | awk -F '"' '{print $4}')
OUTPUT="module Config exposing (..)\n\n$comment\n\n\nconfigName : String\nconfigName =\n    \"$name\"\n\n\nprojectsFileUrl : String\nprojectsFileUrl =\n    \"$proj\""
printf "$OUTPUT" > "src/Config.elm"