module Util.Config exposing (..)

--This file is automatically generated at runtime. Any changes to the file will be lost.


configName : String
configName =
    "Develop"


projectsFileUrl : String
projectsFileUrl =
    "http://localhost:2022/projects/"