module Icon exposing (..)
import Heroicons.Solid
import Html exposing (Html)

type Icon
    = Academiccap
    | Adjustments
    | Annotation
    | Archive
    | Arrowcircledown
    | Arrowcircleleft
    | Arrowcircleright
    | Arrowcircleup
    | Arrowdown
    | Arrowleft
    | Arrownarrowdown
    | Arrownarrowleft
    | Arrownarrowright
    | Arrownarrowup
    | Arrowright
    | Arrowup
    | Arrowsexpand
    | Atsymbol
    | Backspace
    | Badgecheck
    | Ban
    | Beaker
    | Bell
    | Bookopen
    | Bookmarkalt
    | Bookmark
    | Briefcase
    | Cake
    | Calculator
    | Calendar
    | Camera
    | Cash
    | Chartbar
    | Chartpie
    | Chartsquarebar
    | Chatalt2
    | Chatalt
    | Chat
    | Checkcircle
    | Check
    | Chevrondoubledown
    | Chevrondoubleleft
    | Chevrondoubleright
    | Chevrondoubleup
    | Chevrondown
    | Chevronleft
    | Chevronright
    | Chevronup
    | Chip
    | Clipboardcheck
    | Clipboardcopy
    | Clipboardlist
    | Clipboard
    | Clock
    | Clouddownload
    | Cloudupload
    | Cloud
    | Code
    | Cog
    | Collection
    | Colorswatch
    | Creditcard
    | Cubetransparent
    | Cube
    | Currencybangladeshi
    | Currencydollar
    | Currencyeuro
    | Currencypound
    | Currencyrupee
    | Currencyyen
    | Cursorclick
    | Database
    | Desktopcomputer
    | Devicemobile
    | Devicetablet
    | Documentadd
    | Documentdownload
    | Documentduplicate
    | Documentremove
    | Documentreport
    | Documentsearch
    | Documenttext
    | Document
    | Dotscirclehorizontal
    | Dotshorizontal
    | Dotsvertical
    | Download
    | Duplicate
    | Emojihappy
    | Emojisad
    | Exclamationcircle
    | Exclamation
    | Externallink
    | Eyeoff
    | Eye
    | Fastforward
    | Film
    | Filter
    | Fingerprint
    | Fire
    | Flag
    | Folderadd
    | Folderdownload
    | Folderopen
    | Folderremove
    | Folder
    | Gift
    | Globealt
    | Globe
    | Hand
    | Hashtag
    | Heart
    | Home
    | Identification
    | Inboxin
    | Inbox
    | Informationcircle
    | Key
    | Library
    | Lightbulb
    | Lightningbolt
    | Link
    | Locationmarker
    | Lockclosed
    | Lockopen
    | Login
    | Logout
    | Mailopen
    | Mail
    | Map
    | Menualt1
    | Menualt2
    | Menualt3
    | Menualt4
    | Menu
    | Microphone
    | Minuscircle
    | Minussm
    | Minus
    | Moon
    | Musicnote
    | Newspaper
    | Officebuilding
    | Paperairplane
    | Paperclip
    | Pause
    | Pencilalt
    | Pencil
    | Phoneincoming
    | Phonemissedcall
    | Phoneoutgoing
    | Phone
    | Photograph
    | Play
    | Pluscircle
    | Plussm
    | Plus
    | Presentationchartbar
    | Presentationchartline
    | Printer
    | Puzzle
    | Qrcode
    | Questionmarkcircle
    | Receiptrefund
    | Receipttax
    | Refresh
    | Reply
    | Rewind
    | Rss
    | Saveas
    | Save
    | Scale
    | Scissors
    | Searchcircle
    | Search
    | Selector
    | Server
    | Share
    | Shieldcheck
    | Shieldexclamation
    | Shoppingbag
    | Shoppingcart
    | Sortascending
    | Sortdescending
    | Sparkles
    | Speakerphone
    | Star
    | Statusoffline
    | Statusonline
    | Stop
    | Sun
    | Support
    | Switchhorizontal
    | Switchvertical
    | Table
    | Tag
    | Template
    | Terminal
    | Thumbdown
    | Thumbup
    | Ticket
    | Translate
    | Trash
    | Trendingdown
    | Trendingup
    | Truck
    | Upload
    | Useradd
    | Usercircle
    | Usergroup
    | Userremove
    | User
    | Users
    | Variable
    | Videocamera
    | Viewboards
    | Viewgridadd
    | Viewgrid
    | Viewlist
    | Volumeoff
    | Volumeup
    | Wifi
    | Xcircle
    | X
    | Zoomin
    | Zoomout


getHtml: Icon -> Html msg
getHtml icon =
    case icon of
        Academiccap ->
            Heroicons.Solid.academicCap []
        Adjustments ->
            Heroicons.Solid.adjustments []
        Annotation ->
            Heroicons.Solid.annotation []
        Archive ->
            Heroicons.Solid.archive []
        Arrowcircledown ->
            Heroicons.Solid.arrowCircleDown []
        Arrowcircleleft ->
            Heroicons.Solid.arrowCircleLeft []
        Arrowcircleright ->
            Heroicons.Solid.arrowCircleRight []
        Arrowcircleup ->
            Heroicons.Solid.arrowCircleUp []
        Arrowdown ->
            Heroicons.Solid.arrowDown []
        Arrowleft ->
            Heroicons.Solid.arrowLeft []
        Arrownarrowdown ->
            Heroicons.Solid.arrowNarrowDown []
        Arrownarrowleft ->
            Heroicons.Solid.arrowNarrowLeft []
        Arrownarrowright ->
            Heroicons.Solid.arrowNarrowRight []
        Arrownarrowup ->
            Heroicons.Solid.arrowNarrowUp []
        Arrowright ->
            Heroicons.Solid.arrowRight []
        Arrowup ->
            Heroicons.Solid.arrowUp []
        Arrowsexpand ->
            Heroicons.Solid.arrowsExpand []
        Atsymbol ->
            Heroicons.Solid.atSymbol []
        Backspace ->
            Heroicons.Solid.backspace []
        Badgecheck ->
            Heroicons.Solid.badgeCheck []
        Ban ->
            Heroicons.Solid.ban []
        Beaker ->
            Heroicons.Solid.beaker []
        Bell ->
            Heroicons.Solid.bell []
        Bookopen ->
            Heroicons.Solid.bookOpen []
        Bookmarkalt ->
            Heroicons.Solid.bookmarkAlt []
        Bookmark ->
            Heroicons.Solid.bookmark []
        Briefcase ->
            Heroicons.Solid.briefcase []
        Cake ->
            Heroicons.Solid.cake []
        Calculator ->
            Heroicons.Solid.calculator []
        Calendar ->
            Heroicons.Solid.calendar []
        Camera ->
            Heroicons.Solid.camera []
        Cash ->
            Heroicons.Solid.cash []
        Chartbar ->
            Heroicons.Solid.chartBar []
        Chartpie ->
            Heroicons.Solid.chartPie []
        Chartsquarebar ->
            Heroicons.Solid.chartSquareBar []
        Chatalt2 ->
            Heroicons.Solid.chatAlt2 []
        Chatalt ->
            Heroicons.Solid.chatAlt []
        Chat ->
            Heroicons.Solid.chat []
        Checkcircle ->
            Heroicons.Solid.checkCircle []
        Check ->
            Heroicons.Solid.check []
        Chevrondoubledown ->
            Heroicons.Solid.chevronDoubleDown []
        Chevrondoubleleft ->
            Heroicons.Solid.chevronDoubleLeft []
        Chevrondoubleright ->
            Heroicons.Solid.chevronDoubleRight []
        Chevrondoubleup ->
            Heroicons.Solid.chevronDoubleUp []
        Chevrondown ->
            Heroicons.Solid.chevronDown []
        Chevronleft ->
            Heroicons.Solid.chevronLeft []
        Chevronright ->
            Heroicons.Solid.chevronRight []
        Chevronup ->
            Heroicons.Solid.chevronUp []
        Chip ->
            Heroicons.Solid.chip []
        Clipboardcheck ->
            Heroicons.Solid.clipboardCheck []
        Clipboardcopy ->
            Heroicons.Solid.clipboardCopy []
        Clipboardlist ->
            Heroicons.Solid.clipboardList []
        Clipboard ->
            Heroicons.Solid.clipboard []
        Clock ->
            Heroicons.Solid.clock []
        Clouddownload ->
            Heroicons.Solid.cloudDownload []
        Cloudupload ->
            Heroicons.Solid.cloudUpload []
        Cloud ->
            Heroicons.Solid.cloud []
        Code ->
            Heroicons.Solid.code []
        Cog ->
            Heroicons.Solid.cog []
        Collection ->
            Heroicons.Solid.collection []
        Colorswatch ->
            Heroicons.Solid.colorSwatch []
        Creditcard ->
            Heroicons.Solid.creditCard []
        Cubetransparent ->
            Heroicons.Solid.cubeTransparent []
        Cube ->
            Heroicons.Solid.cube []
        Currencybangladeshi ->
            Heroicons.Solid.currencyBangladeshi []
        Currencydollar ->
            Heroicons.Solid.currencyDollar []
        Currencyeuro ->
            Heroicons.Solid.currencyEuro []
        Currencypound ->
            Heroicons.Solid.currencyPound []
        Currencyrupee ->
            Heroicons.Solid.currencyRupee []
        Currencyyen ->
            Heroicons.Solid.currencyYen []
        Cursorclick ->
            Heroicons.Solid.cursorClick []
        Database ->
            Heroicons.Solid.database []
        Desktopcomputer ->
            Heroicons.Solid.desktopComputer []
        Devicemobile ->
            Heroicons.Solid.deviceMobile []
        Devicetablet ->
            Heroicons.Solid.deviceTablet []
        Documentadd ->
            Heroicons.Solid.documentAdd []
        Documentdownload ->
            Heroicons.Solid.documentDownload []
        Documentduplicate ->
            Heroicons.Solid.documentDuplicate []
        Documentremove ->
            Heroicons.Solid.documentRemove []
        Documentreport ->
            Heroicons.Solid.documentReport []
        Documentsearch ->
            Heroicons.Solid.documentSearch []
        Documenttext ->
            Heroicons.Solid.documentText []
        Document ->
            Heroicons.Solid.document []
        Dotscirclehorizontal ->
            Heroicons.Solid.dotsCircleHorizontal []
        Dotshorizontal ->
            Heroicons.Solid.dotsHorizontal []
        Dotsvertical ->
            Heroicons.Solid.dotsVertical []
        Download ->
            Heroicons.Solid.download []
        Duplicate ->
            Heroicons.Solid.duplicate []
        Emojihappy ->
            Heroicons.Solid.emojiHappy []
        Emojisad ->
            Heroicons.Solid.emojiSad []
        Exclamationcircle ->
            Heroicons.Solid.exclamationCircle []
        Exclamation ->
            Heroicons.Solid.exclamation []
        Externallink ->
            Heroicons.Solid.externalLink []
        Eyeoff ->
            Heroicons.Solid.eyeOff []
        Eye ->
            Heroicons.Solid.eye []
        Fastforward ->
            Heroicons.Solid.fastForward []
        Film ->
            Heroicons.Solid.film []
        Filter ->
            Heroicons.Solid.filter []
        Fingerprint ->
            Heroicons.Solid.fingerPrint []
        Fire ->
            Heroicons.Solid.fire []
        Flag ->
            Heroicons.Solid.flag []
        Folderadd ->
            Heroicons.Solid.folderAdd []
        Folderdownload ->
            Heroicons.Solid.folderDownload []
        Folderopen ->
            Heroicons.Solid.folderOpen []
        Folderremove ->
            Heroicons.Solid.folderRemove []
        Folder ->
            Heroicons.Solid.folder []
        Gift ->
            Heroicons.Solid.gift []
        Globealt ->
            Heroicons.Solid.globeAlt []
        Globe ->
            Heroicons.Solid.globe []
        Hand ->
            Heroicons.Solid.hand []
        Hashtag ->
            Heroicons.Solid.hashtag []
        Heart ->
            Heroicons.Solid.heart []
        Home ->
            Heroicons.Solid.home []
        Identification ->
            Heroicons.Solid.identification []
        Inboxin ->
            Heroicons.Solid.inboxIn []
        Inbox ->
            Heroicons.Solid.inbox []
        Informationcircle ->
            Heroicons.Solid.informationCircle []
        Key ->
            Heroicons.Solid.key []
        Library ->
            Heroicons.Solid.library []
        Lightbulb ->
            Heroicons.Solid.lightBulb []
        Lightningbolt ->
            Heroicons.Solid.lightningBolt []
        Link ->
            Heroicons.Solid.link []
        Locationmarker ->
            Heroicons.Solid.locationMarker []
        Lockclosed ->
            Heroicons.Solid.lockClosed []
        Lockopen ->
            Heroicons.Solid.lockOpen []
        Login ->
            Heroicons.Solid.login []
        Logout ->
            Heroicons.Solid.logout []
        Mailopen ->
            Heroicons.Solid.mailOpen []
        Mail ->
            Heroicons.Solid.mail []
        Map ->
            Heroicons.Solid.map []
        Menualt1 ->
            Heroicons.Solid.menuAlt1 []
        Menualt2 ->
            Heroicons.Solid.menuAlt2 []
        Menualt3 ->
            Heroicons.Solid.menuAlt3 []
        Menualt4 ->
            Heroicons.Solid.menuAlt4 []
        Menu ->
            Heroicons.Solid.menu []
        Microphone ->
            Heroicons.Solid.microphone []
        Minuscircle ->
            Heroicons.Solid.minusCircle []
        Minussm ->
            Heroicons.Solid.minusSm []
        Minus ->
            Heroicons.Solid.minus []
        Moon ->
            Heroicons.Solid.moon []
        Musicnote ->
            Heroicons.Solid.musicNote []
        Newspaper ->
            Heroicons.Solid.newspaper []
        Officebuilding ->
            Heroicons.Solid.officeBuilding []
        Paperairplane ->
            Heroicons.Solid.paperAirplane []
        Paperclip ->
            Heroicons.Solid.paperClip []
        Pause ->
            Heroicons.Solid.pause []
        Pencilalt ->
            Heroicons.Solid.pencilAlt []
        Pencil ->
            Heroicons.Solid.pencil []
        Phoneincoming ->
            Heroicons.Solid.phoneIncoming []
        Phonemissedcall ->
            Heroicons.Solid.phoneMissedCall []
        Phoneoutgoing ->
            Heroicons.Solid.phoneOutgoing []
        Phone ->
            Heroicons.Solid.phone []
        Photograph ->
            Heroicons.Solid.photograph []
        Play ->
            Heroicons.Solid.play []
        Pluscircle ->
            Heroicons.Solid.plusCircle []
        Plussm ->
            Heroicons.Solid.plusSm []
        Plus ->
            Heroicons.Solid.plus []
        Presentationchartbar ->
            Heroicons.Solid.presentationChartBar []
        Presentationchartline ->
            Heroicons.Solid.presentationChartLine []
        Printer ->
            Heroicons.Solid.printer []
        Puzzle ->
            Heroicons.Solid.puzzle []
        Qrcode ->
            Heroicons.Solid.qrcode []
        Questionmarkcircle ->
            Heroicons.Solid.questionMarkCircle []
        Receiptrefund ->
            Heroicons.Solid.receiptRefund []
        Receipttax ->
            Heroicons.Solid.receiptTax []
        Refresh ->
            Heroicons.Solid.refresh []
        Reply ->
            Heroicons.Solid.reply []
        Rewind ->
            Heroicons.Solid.rewind []
        Rss ->
            Heroicons.Solid.rss []
        Saveas ->
            Heroicons.Solid.saveAs []
        Save ->
            Heroicons.Solid.save []
        Scale ->
            Heroicons.Solid.scale []
        Scissors ->
            Heroicons.Solid.scissors []
        Searchcircle ->
            Heroicons.Solid.searchCircle []
        Search ->
            Heroicons.Solid.search []
        Selector ->
            Heroicons.Solid.selector []
        Server ->
            Heroicons.Solid.server []
        Share ->
            Heroicons.Solid.share []
        Shieldcheck ->
            Heroicons.Solid.shieldCheck []
        Shieldexclamation ->
            Heroicons.Solid.shieldExclamation []
        Shoppingbag ->
            Heroicons.Solid.shoppingBag []
        Shoppingcart ->
            Heroicons.Solid.shoppingCart []
        Sortascending ->
            Heroicons.Solid.sortAscending []
        Sortdescending ->
            Heroicons.Solid.sortDescending []
        Sparkles ->
            Heroicons.Solid.sparkles []
        Speakerphone ->
            Heroicons.Solid.speakerphone []
        Star ->
            Heroicons.Solid.star []
        Statusoffline ->
            Heroicons.Solid.statusOffline []
        Statusonline ->
            Heroicons.Solid.statusOnline []
        Stop ->
            Heroicons.Solid.stop []
        Sun ->
            Heroicons.Solid.sun []
        Support ->
            Heroicons.Solid.support []
        Switchhorizontal ->
            Heroicons.Solid.switchHorizontal []
        Switchvertical ->
            Heroicons.Solid.switchVertical []
        Table ->
            Heroicons.Solid.table []
        Tag ->
            Heroicons.Solid.tag []
        Template ->
            Heroicons.Solid.template []
        Terminal ->
            Heroicons.Solid.terminal []
        Thumbdown ->
            Heroicons.Solid.thumbDown []
        Thumbup ->
            Heroicons.Solid.thumbUp []
        Ticket ->
            Heroicons.Solid.ticket []
        Translate ->
            Heroicons.Solid.translate []
        Trash ->
            Heroicons.Solid.trash []
        Trendingdown ->
            Heroicons.Solid.trendingDown []
        Trendingup ->
            Heroicons.Solid.trendingUp []
        Truck ->
            Heroicons.Solid.truck []
        Upload ->
            Heroicons.Solid.upload []
        Useradd ->
            Heroicons.Solid.userAdd []
        Usercircle ->
            Heroicons.Solid.userCircle []
        Usergroup ->
            Heroicons.Solid.userGroup []
        Userremove ->
            Heroicons.Solid.userRemove []
        User ->
            Heroicons.Solid.user []
        Users ->
            Heroicons.Solid.users []
        Variable ->
            Heroicons.Solid.variable []
        Videocamera ->
            Heroicons.Solid.videoCamera []
        Viewboards ->
            Heroicons.Solid.viewBoards []
        Viewgridadd ->
            Heroicons.Solid.viewGridAdd []
        Viewgrid ->
            Heroicons.Solid.viewGrid []
        Viewlist ->
            Heroicons.Solid.viewList []
        Volumeoff ->
            Heroicons.Solid.volumeOff []
        Volumeup ->
            Heroicons.Solid.volumeUp []
        Wifi ->
            Heroicons.Solid.wifi []
        Xcircle ->
            Heroicons.Solid.xCircle []
        X ->
            Heroicons.Solid.x []
        Zoomin ->
            Heroicons.Solid.zoomIn []
        Zoomout ->
            Heroicons.Solid.zoomOut []
